var javascriptIsCool = true;
console.log(javascriptIsCool);
var hadShower = true;
var hasBackpack = false;
console.log(hadShower && hasBackpack);
var hadShower = true;
var hasBackpack = true;
console.log(hadShower && hasBackpack);
var hasApple = true;
var hasOrange = false;
console.log(hasApple || hasOrange);
var isWeekend = true;
var needToShowerTodey = !isWeekend;
console.log(needToShowerTodey);
var isWeekend = false;
var hadShower = true;
var hasApple = false;
var hasOrange = true;
var shouldGoToSchool = !isWeekend && hadShower && (hasApple || hasOrange);
console.log(shouldGoToSchool);
var height = 76;
var heightRestriction = 60;
console.log(height > heightRestriction);
var height = 60;
var heightRestriction = 60;
console.log(height > heightRestriction);
var height = 60;
var heightRestriction = 60;
console.log(height >= heightRestriction);
var height = 60;
var heightRestriction = 48;
console.log(height < heightRestriction);