var animals = [];
animals.push("Cat");
console.log(animals.push("Cat"));
animals.push("Dog");
console.log(animals.push("Dog"));
animals.push("Llama");
console.log(animals.push("Llama"));
animals.push();
[ "Cat", "Dog", "Llama" ];
console.log(animals.length);