var animals = [];
animals.push("Cat");
animals.push("Dog");
animals.push("Llama");
console.log(animals);
console.log(animals.length);
console.log(animals[0]);
console.log(animals.unshift("Monkey"));
console.log(animals);
console.log(animals.unshift("Polar Bear"));
console.log(animals);
console.log(animals[0]);
console.log(animals[2]);
console.log(animals);
var lastAnimal = animals.pop();
console.log(lastAnimal);
console.log(animals);
console.log(animals.pop());
console.log(animals);
console.log(animals.unshift(lastAnimal));
console.log(animals);
var firstAnimal = animals.shift();
console.log(firstAnimal);
console.log(animals);
