var animals = [];
animals.push("Cat");
animals.push("Dog");
animals.push("Llama");
console.log(animals);
console.log(animals.length);
console.log(animals[0]);
console.log(animals.unshift("Monkey"));
console.log(animals);
console.log(animals.unshift("Polar Bear"));
console.log(animals);
console.log(animals[0]);
console.log(animals[2]);
console.log(animals);
var lastAnimal = animals.pop();
console.log(lastAnimal);
console.log(animals);
console.log(animals.pop());
console.log(animals);
console.log(animals.unshift(lastAnimal));
console.log(animals);
var firstAnimal = animals.shift();
console.log(firstAnimal);
console.log(animals);
var furryAnimals =["Alpaca","Ring-tailed Lemur","Yeti"];
var sclayAnimals =["Boa Constrictor","Godzilla"];
var furryAndsclayAnimals = furryAnimals.concat(sclayAnimals);
console.log(furryAndsclayAnimals);
console.log(furryAnimals);
console.log(sclayAnimals);
var furryAnimals =["Alpaca","Ring-tailed Lemur","Yeti"];
var sclayAnimals =["Boa Constrictor","Godzilla"];
var featheredAnimals = ["Macaw", "Dodo"];
var allAnimals = furryAnimals.concat(sclayAnimals, featheredAnimals);
console.log(allAnimals);
var colors = ["red", "green", "blue"];
console.log(colors.indexOf("blue"));
console.log(colors.indexOf("green"));
console.log(colors[2]);
console.log(colors.indexOf("blue"));
console.log(colors.indexOf("purple"));
var insects = ["Bee", "Ant", "Bee", "Bee", "Ant"];
console.log(insects.indexOf("Bee"));
var boringAnimals = ["Monkey", "Cat", "Fish", "Lizard"];
console.log(boringAnimals.join());
var boringAnimals = ["Monkey", "Cat", "Fish", "Lizard"];
console.log(boringAnimals.join("-"));
console.log(boringAnimals.join("*"));
console.log(boringAnimals.join(" sees "));
var myName = ["Vova", " Stas", " Yura", " Evgen"];
console.log(myName.join(""));
var ages = [51, 27, 24, 21];
console.log(ages.join(""));
