var myAwesomeString = "Something REALLY awesome!";
console.log(myAwesomeString);
var myThing = 5;
myThing = "this is a string";
console.log(myThing);
var numberNine = 9;
console.log(numberNine + numberNine);
var stringNine = "9";
console.log(stringNine + stringNine);
var greeting = "Hello";
var myName = " Evgen";
console.log(greeting + myName);
var java = "Java";
console.log(java.length);
var name = "Evgeniy";
console.log(name.length);
var name = "Vladimir";
console.log(name.length);
var myName = "Evgeniy";
console.log(myName[0]);
console.log(myName[1]);
console.log(myName[2]);
console.log(myName[3]);
console.log(myName[4]);
console.log(myName[5]);
console.log(myName[6]);
var codeWord1 = "are";
var codeWord2 = "people";
var codeWord3 = "open";
var codeWord4 = "hello";
var codeWord5 = "help";
var codeWord6 = "?!";
console.log(codeWord1[0] + codeWord2[0] + codeWord3[1] + codeWord4[2] + codeWord5[1] + codeWord6[1]);
var longString = "My long string is long";
console.log(longString.slice(3,14));
var longString = "My long string is long";
console.log(longString.slice(3));
console.log("Hello there, how are you doing?".toUpperCase());
console.log("Hello there, how are you doing?".toLowerCase());
var sillyString = "hELlo THERE, how ARE yOu doINg?";
var lowerString = sillyString.toLowerCase();
var firstCharacter = lowerString[0];
var firstCharacterUpper = firstCharacter.toUpperCase();
var restOfString = lowerString.slice(1);
console.log(firstCharacterUpper + restOfString);

