var nick;
console.log(nick);
let age = 12;
console.log(age);
age = 13;
console.log(age);
var numberOfSiblings = 1 + 3;
var numberOfCondies = 8;
console.log(numberOfCondies / numberOfSiblings);
var secondsInAMinete = 60;
var minutesInAnHour = 60;
var secondsInAnHour = secondsInAMinete * minutesInAnHour;
console.log(secondsInAnHour);
var hoursInADay = 24;
var secondsInADay = secondsInAnHour * hoursInADay;
console.log(secondsInADay);
var daysInYear = 365;
var secondsInYear = secondsInADay * daysInYear;
console.log(secondsInYear);
age = 22;
console.log(age * secondsInYear);
var highFives = 0;
console.log(++highFives);
console.log(++highFives);
console.log(--highFives);
highFives = 0;
console.log(highFives++);
console.log(highFives++);
console.log(highFives);
var x = 17;
x = x + 5;
console.log(x);
var score = 67;
console.log(score += 23);
console.log(score -= 15);
var balloons = 100;
console.log(balloons *= 2);
var balloons = 100;
console.log(balloons /= 4);